[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Macros to derive runtime debug implementation."
documentation = "https://docs.rs/sp-debug-derive"
edition = "2018"
homepage = "https://substrate.dev"
license = "Apache-2.0"
name = "sp-debug-derive"
repository = "https://github.com/paritytech/substrate/"
version = "3.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0.3"
syn = "1.0.58"

[features]
std = []

[dev-dependencies]
